### ISSUE TITLE
Error in data retrieving

### ISSUE THREAD

**Issue by fabianoP** [Spine-project/MetReLoad#1]
when I use the package trying to retrieve data from the merra collection in this way:

data = mr.get_merra2_collection_dataframe('M2I1NXASM', "myusername", "mypassword", "2015-01-01", "2015-01-02", ["T2M"],(53.3498,6.2603) )

I get this error:
[D 200520 11:00:53 merra2:133] Setting up session to https://goldsmr4.gesdisc.eosdis.nasa.gov/dods/M2I1NXASM as fabianop
[D 200520 11:01:01 merra2:140] Opening Pydap data store
[D 200520 11:01:05 merra2:152] Opening dataset
[D 200520 11:01:28 merra2:96] Making a subset copy
[D 200520 11:01:28 merra2:217] Subsetting dataset
[D 200520 11:01:28 merra2:196] Loading dask array to memory

tests\test_merra2_server.py:2 (test_merra2_collection_to_dataframe)
self = <DatasetType with children 't2m'>, key = 't2m.t2m'

    def _getitem_string(self, key):
        """ Assume that key is a string type """
        try:
>           return self._dict[quote(key)]
E           KeyError: 't2m%2Et2m'

C:\ProgramData\Anaconda3\envs\MetReLoad\lib\site-packages\pydap\model.py:404: KeyError

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by ghost** [comment]
I’ve seen this one before, and it might be due to an old version of pydap library. Latest release 3.2.2 (from May 2017!) does not work, but you need commit 4ba09cad74de2e47ab898c45b1e2af1fe7e5bb4e or later (see requirements.txt). Could check what you have installed? (Installing the specific commit `pip freeze` still shows that you have version 3.2.2 installed, because that’s the latest.)

**Comment by fabianoP** [comment]
I have just bumped the installed to the latest one and seems to work

git+https://github.com/pydap/pydap@3f6aa190c59e3bbc6c834377a61579b20275ff69

Fabiano
